{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPyd68NnIgnVR39LMDKBCMA",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/cuty-sj/PASS-Review-Agent/blob/main/PASS_Android_Appreview.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "eLWav9wxR1RD"
      },
      "outputs": [],
      "source": []
    },
    {
      "cell_type": "code",
      "source": [
        "# ==========================================\n",
        "# PASS Android Review Report\n",
        "# ==========================================\n",
        "\n",
        "from google_play_scraper import reviews\n",
        "import pandas as pd\n",
        "from datetime import datetime, timedelta\n",
        "import requests\n",
        "\n",
        "# ==========================================\n",
        "# Telegram 설정\n",
        "# ==========================================\n",
        "\n",
        "BOT_TOKEN = \"8678809011:AAF0D6mYSyXqKR7JfFrPUKzqdHBoKzgPFOQ\"\n",
        "CHAT_ID = \"6526825018\"\n",
        "\n",
        "# ==========================================\n",
        "# 리뷰 수집\n",
        "# ==========================================\n",
        "\n",
        "result, _ = reviews(\n",
        "    'com.sktelecom.tauth',\n",
        "    lang='ko',\n",
        "    country='kr',\n",
        "    count=500\n",
        ")\n",
        "\n",
        "review_list = []\n",
        "\n",
        "for r in result:\n",
        "    review_list.append({\n",
        "        \"작성일\": pd.to_datetime(r[\"at\"]),\n",
        "        \"작성자\": r[\"userName\"],\n",
        "        \"평점\": int(r[\"score\"]),\n",
        "        \"리뷰내용\": str(r[\"content\"])\n",
        "    })\n",
        "\n",
        "df = pd.DataFrame(review_list)\n",
        "\n",
        "# ==========================================\n",
        "# 분석기간\n",
        "# 현재일 -8일 ~ 현재일 -1일\n",
        "# ==========================================\n",
        "\n",
        "today = datetime.now()\n",
        "\n",
        "start_date = today - timedelta(days=8)\n",
        "end_date = today - timedelta(days=1)\n",
        "\n",
        "recent_df = df[\n",
        "    (df[\"작성일\"] >= start_date) &\n",
        "    (df[\"작성일\"] <= end_date)\n",
        "].copy()\n",
        "\n",
        "# ==========================================\n",
        "# 리뷰 통계\n",
        "# ==========================================\n",
        "\n",
        "review_count = len(recent_df)\n",
        "\n",
        "avg_score = (\n",
        "    round(recent_df[\"평점\"].mean(), 2)\n",
        "    if review_count > 0\n",
        "    else 0\n",
        ")\n",
        "\n",
        "# ==========================================\n",
        "# 긍정 리뷰 TOP3\n",
        "# ==========================================\n",
        "\n",
        "positive_reviews = recent_df[\n",
        "    recent_df[\"평점\"] >= 4\n",
        "].sort_values(\n",
        "    by=[\"평점\", \"작성일\"],\n",
        "    ascending=[False, False]\n",
        ").head(3)\n",
        "\n",
        "# ==========================================\n",
        "# 부정 리뷰 TOP5\n",
        "# ==========================================\n",
        "\n",
        "negative_reviews = recent_df[\n",
        "    recent_df[\"평점\"] <= 2\n",
        "].sort_values(\n",
        "    by=[\"평점\", \"작성일\"],\n",
        "    ascending=[True, False]\n",
        ").head(5)\n",
        "\n",
        "# ==========================================\n",
        "# 메시지 생성\n",
        "# ==========================================\n",
        "\n",
        "nums = [\"①\", \"②\", \"③\", \"④\", \"⑤\"]\n",
        "\n",
        "message = \"\"\n",
        "\n",
        "message += \"📱 PASS Android Review Report\\n\"\n",
        "\n",
        "message += \"━━━━━━━━━━━━━━━\\n\\n\"\n",
        "\n",
        "message += \"📅 분석 기간\\n\"\n",
        "message += (\n",
        "    f\"{start_date.strftime('%Y.%m.%d')} ~ \"\n",
        "    f\"{end_date.strftime('%Y.%m.%d')}\\n\\n\"\n",
        ")\n",
        "\n",
        "message += \"⭐ 리뷰 현황\\n\"\n",
        "message += f\"• 평균 별점 : {avg_score}점 / 5점\\n\"\n",
        "message += f\"• 리뷰 수 : 총 {review_count}건\\n\\n\"\n",
        "\n",
        "# ==========================================\n",
        "# 긍정 리뷰 TOP3\n",
        "# ==========================================\n",
        "\n",
        "message += \"───────────────\\n\\n\"\n",
        "\n",
        "message += \"👍 긍정 리뷰 (별점 4개 이상)\\n\\n\"\n",
        "\n",
        "if len(positive_reviews) == 0:\n",
        "\n",
        "    message += \"• 해당 기간 리뷰 없음\\n\\n\"\n",
        "\n",
        "else:\n",
        "\n",
        "    for idx, row in enumerate(\n",
        "        positive_reviews.itertuples()\n",
        "    ):\n",
        "\n",
        "        review = (\n",
        "            row.리뷰내용[:120]\n",
        "            .replace(\"\\n\", \" \")\n",
        "            .strip()\n",
        "        )\n",
        "\n",
        "        message += f\"{nums[idx]} {review}\\n\"\n",
        "\n",
        "# ==========================================\n",
        "# 부정 리뷰 TOP5\n",
        "# ==========================================\n",
        "\n",
        "message += \"\\n\\n👎 부정 리뷰 (별점 2개 이하)\\n\\n\"\n",
        "\n",
        "if len(negative_reviews) == 0:\n",
        "\n",
        "    message += \"• 해당 기간 리뷰 없음\\n\\n\"\n",
        "\n",
        "else:\n",
        "\n",
        "    for idx, row in enumerate(\n",
        "        negative_reviews.itertuples()\n",
        "    ):\n",
        "\n",
        "        review = (\n",
        "            row.리뷰내용[:150]\n",
        "            .replace(\"\\n\", \" \")\n",
        "            .strip()\n",
        "        )\n",
        "\n",
        "        message += f\"{nums[idx]} {review}\\n\"\n",
        "\n",
        "# ==========================================\n",
        "# Store 링크\n",
        "# ==========================================\n",
        "\n",
        "message += \"\\n───────────────\\n\\n\"\n",
        "\n",
        "message += \"아래 링크로 🔍 Store Review 보러가기\\n\\n\"\n",
        "\n",
        "message += (\n",
        "    \"Android\\n\"\n",
        "    \"https://play.google.com/store/apps/details\"\n",
        "    \"?id=com.sktelecom.tauth&showAllReviews=true\"\n",
        ")\n",
        "\n",
        "# 텔레그램 제한 대응\n",
        "message = message[:3900]\n",
        "\n",
        "# ==========================================\n",
        "# 콘솔 확인\n",
        "# ==========================================\n",
        "\n",
        "print(message)\n",
        "\n",
        "# ==========================================\n",
        "# Telegram 발송\n",
        "# ==========================================\n",
        "\n",
        "url = (\n",
        "    f\"https://api.telegram.org/bot\"\n",
        "    f\"{BOT_TOKEN}/sendMessage\"\n",
        ")\n",
        "\n",
        "response = requests.post(\n",
        "    url,\n",
        "    data={\n",
        "        \"chat_id\": CHAT_ID,\n",
        "        \"text\": message\n",
        "    }\n",
        ")\n",
        "\n",
        "print(\"\\n전송결과 :\", response.status_code)\n",
        "print(response.text)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "h7_GUDk0bBOt",
        "outputId": "438f0dce-567c-4c79-9635-4f17b89364be"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "📱 PASS Android Review Report\n",
            "━━━━━━━━━━━━━━━\n",
            "\n",
            "📅 분석 기간\n",
            "2026.06.18 ~ 2026.06.25\n",
            "\n",
            "⭐ 리뷰 현황\n",
            "• 평균 별점 : 3.0점 / 5점\n",
            "• 리뷰 수 : 총 5건\n",
            "\n",
            "───────────────\n",
            "\n",
            "👍 긍정 리뷰 (별점 4개 이상)\n",
            "\n",
            "① 감사~\n",
            "② ' - . . 1 . 1\n",
            "③ 좋아요.고령자에도\n",
            "\n",
            "\n",
            "👎 부정 리뷰 (별점 2개 이하)\n",
            "\n",
            "① 앱이 서버연동도 안되고. 해서 고객센터 전화를 오전10시부터 오후2시35분까지 꾸준히 해도 연결이 안되네 결론은 고객센터는 없다.\n",
            "② 설정에서 모든 광고 알림 차단해두었으나 가끔 알림표시줄에 PASS 광고 알림이 옵니다 이상해서 다시 설정에 들어가 확인해도 광고 관련 알림은 다 off로 설정되어 있습니다\n",
            "\n",
            "───────────────\n",
            "\n",
            "아래 링크로 🔍 Store Review 보러가기\n",
            "\n",
            "Android\n",
            "https://play.google.com/store/apps/details?id=com.sktelecom.tauth&showAllReviews=true\n",
            "\n",
            "전송결과 : 200\n",
            "{\"ok\":true,\"result\":{\"message_id\":24,\"from\":{\"id\":8678809011,\"is_bot\":true,\"first_name\":\"PASS Reviewbot\",\"username\":\"PASS_ReviewBot\"},\"chat\":{\"id\":6526825018,\"first_name\":\"\\ubc15\\uc218\\uc815\",\"type\":\"private\"},\"date\":1782483049,\"text\":\"\\ud83d\\udcf1 PASS Android Review Report\\n\\u2501\\u2501\\u2501\\u2501\\u2501\\u2501\\u2501\\u2501\\u2501\\u2501\\u2501\\u2501\\u2501\\u2501\\u2501\\n\\n\\ud83d\\udcc5 \\ubd84\\uc11d \\uae30\\uac04\\n2026.06.18 ~ 2026.06.25\\n\\n\\u2b50 \\ub9ac\\ubdf0 \\ud604\\ud669\\n\\u2022 \\ud3c9\\uade0 \\ubcc4\\uc810 : 3.0\\uc810 / 5\\uc810\\n\\u2022 \\ub9ac\\ubdf0 \\uc218 : \\ucd1d 5\\uac74\\n\\n\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\n\\n\\ud83d\\udc4d \\uae0d\\uc815 \\ub9ac\\ubdf0 (\\ubcc4\\uc810 4\\uac1c \\uc774\\uc0c1)\\n\\n\\u2460 \\uac10\\uc0ac~\\n\\u2461 ' - . . 1 . 1\\n\\u2462 \\uc88b\\uc544\\uc694.\\uace0\\ub839\\uc790\\uc5d0\\ub3c4\\n\\n\\n\\ud83d\\udc4e \\ubd80\\uc815 \\ub9ac\\ubdf0 (\\ubcc4\\uc810 2\\uac1c \\uc774\\ud558)\\n\\n\\u2460 \\uc571\\uc774 \\uc11c\\ubc84\\uc5f0\\ub3d9\\ub3c4 \\uc548\\ub418\\uace0. \\ud574\\uc11c \\uace0\\uac1d\\uc13c\\ud130 \\uc804\\ud654\\ub97c \\uc624\\uc80410\\uc2dc\\ubd80\\ud130 \\uc624\\ud6c42\\uc2dc35\\ubd84\\uae4c\\uc9c0 \\uafb8\\uc900\\ud788 \\ud574\\ub3c4 \\uc5f0\\uacb0\\uc774 \\uc548\\ub418\\ub124 \\uacb0\\ub860\\uc740 \\uace0\\uac1d\\uc13c\\ud130\\ub294 \\uc5c6\\ub2e4.\\n\\u2461 \\uc124\\uc815\\uc5d0\\uc11c \\ubaa8\\ub4e0 \\uad11\\uace0 \\uc54c\\ub9bc \\ucc28\\ub2e8\\ud574\\ub450\\uc5c8\\uc73c\\ub098 \\uac00\\ub054 \\uc54c\\ub9bc\\ud45c\\uc2dc\\uc904\\uc5d0 PASS \\uad11\\uace0 \\uc54c\\ub9bc\\uc774 \\uc635\\ub2c8\\ub2e4 \\uc774\\uc0c1\\ud574\\uc11c \\ub2e4\\uc2dc \\uc124\\uc815\\uc5d0 \\ub4e4\\uc5b4\\uac00 \\ud655\\uc778\\ud574\\ub3c4 \\uad11\\uace0 \\uad00\\ub828 \\uc54c\\ub9bc\\uc740 \\ub2e4 off\\ub85c \\uc124\\uc815\\ub418\\uc5b4 \\uc788\\uc2b5\\ub2c8\\ub2e4\\n\\n\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\n\\n\\uc544\\ub798 \\ub9c1\\ud06c\\ub85c \\ud83d\\udd0d Store Review \\ubcf4\\ub7ec\\uac00\\uae30\\n\\nAndroid\\nhttps://play.google.com/store/apps/details?id=com.sktelecom.tauth&showAllReviews=true\",\"entities\":[{\"offset\":447,\"length\":85,\"type\":\"url\"}],\"link_preview_options\":{\"url\":\"https://play.google.com/store/apps/details?id=com.sktelecom.tauth&showAllReviews=true\"}}}\n"
          ]
        }
      ]
    }
  ]
}